'use client';

import Link from 'next/link';
import styles from './page.module.css';

export default function PrivacyPage() {
  return (
    <>
      <a href="#main-content" className="skip-link">
        Skip to main content
      </a>

      <header className={styles.header}>
        <div className={styles.headerContent}>
          <h1 className={styles.title}>Privacy Policy</h1>
          <p className={styles.subtitle}>
            Your privacy is our priority. Here&apos;s how we protect it.
          </p>
        </div>
      </header>

      <main id="main-content" className={styles.main}>
        <article className={styles.content}>
          <section className={styles.section}>
            <h2 className={styles.sectionHeading}>Our Commitment</h2>
            <p>
              Contact Your Representatives is built with privacy as a core principle.
              We believe you should be able to engage with your elected officials
              without sacrificing your personal information.
            </p>
          </section>

          <section className={styles.section}>
            <h2 className={styles.sectionHeading}>No Data Storage</h2>
            <p>
              We do not store your ZIP code, issue selections, or any other information
              you enter into this application. All data exists only in your browser
              during your session and is cleared when you close the page.
            </p>
            <ul className={styles.list}>
              <li>Your ZIP code is only used to look up your representatives</li>
              <li>Your issue selections are only used to generate your message</li>
              <li>Nothing is saved to any database or server</li>
            </ul>
          </section>

          <section className={styles.section}>
            <h2 className={styles.sectionHeading}>No Message Sending</h2>
            <p>
              We never send messages on your behalf. The message generated by this
              tool is copied to your clipboard, and you manually paste it into your
              representative&apos;s official contact form. This ensures:
            </p>
            <ul className={styles.list}>
              <li>You maintain full control over what is sent</li>
              <li>You can review and edit the message before sending</li>
              <li>Your message goes directly to your representative, not through us</li>
            </ul>
          </section>

          <section className={styles.section}>
            <h2 className={styles.sectionHeading}>No Tracking</h2>
            <p>
              We use Vercel Analytics solely to measure aggregate traffic volume (page views and visitor counts).
              It does not track individual users:
            </p>
            <ul className={styles.list}>
              <li>No cookies</li>
              <li>No fingerprinting</li>
              <li>No personal data collected</li>
              <li>No local storage persistence</li>
              <li>No third-party tracking pixels</li>
            </ul>
            <p>
              The analytics data is anonymous and aggregated — it tells us how many people visited the site,
              not who they are or what they did.
            </p>
          </section>

          <section className={styles.section}>
            <h2 className={styles.sectionHeading}>Third-Party Services</h2>
            <p>
              This application uses the <a href="https://5calls.org/representatives-api/" target="_blank" rel="noopener noreferrer">5calls.org API</a> to
              look up representative information based on your ZIP code. When you
              submit your ZIP code, it is sent to their service to retrieve your
              representatives. Please refer to 5calls.org for their privacy practices.
            </p>
            <p>
              We do not share any other information with third parties.
            </p>
          </section>

          <section className={styles.section}>
            <h2 className={styles.sectionHeading}>Open Source</h2>
            <p>
              This application is open source under the MIT License.
              The source code is publicly available for review so you can verify our privacy practices.
            </p>
          </section>

          <div className={styles.backLink}>
            <Link href="/">
              &larr; Back to Contact Your Representatives
            </Link>
          </div>
        </article>
      </main>

      <footer className={styles.footer}>
        <div className={styles.footerContent}>
          <p className={styles.disclaimer}>
            This is an independent, open-source project and is not affiliated with,
            endorsed by, or connected to the U.S. government or any government agency.
          </p>
          <p className={styles.footerLinks}>
            <Link href="/about">About</Link>
            {' · '}
            <span>MIT License</span>
          </p>
        </div>
      </footer>
    </>
  );
}
